# data parameters
#dataset_name: imagenet
train_data_path: /media/jamin/4.0TB/mydata_v3
val_data_path:
resume: /anything_in_anyscene/models/zhangzr/style_transfer/anticollision_v2
infer_checkpoint_path: /anything_in_anyscene/models/zhangzr/style_transfer/normal_v2 # normal_v1 normal_v3
batch_size: 12
image_shape: [256, 256, 3]
mask_shape: [128, 128]
mask_batch_same: True
# max_delta_shape: [32, 32] 
max_delta_shape: [0, 0] 
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: True
#mask_type: hole     # hole | mosaic
mosaic_unit_size: 12

# training parameters
#expname: benchmark
cuda: True
# gpu_ids: [0, 1, 2]    # set the GPU ids to use, e.g. [0] or [1, 2]
gpu_ids: [0] 
num_workers: 4
lr: 0.0001
beta1: 0.5
beta2: 0.9
n_critic: 5
niter: 500000
print_iter: 100
viz_iter: 100
viz_max_out: 8
snapshot_save_iter: 5000

# loss weight
# coarse_l1_alpha: 1.2
# l1_loss_alpha: 1.2
# ae_loss_alpha: 1.2
# global_wgan_loss_alpha: 1.
# gan_loss_alpha: 0.001
# wgan_gp_lambda: 10

l1_loss_alpha: 0.1
ae_loss_alpha: 0.1
gan_loss_alpha: 0.001
wgan_gp_lambda: 10
vgg_loss_alpha: 1.

coarse_l1_alpha: 0.1
global_wgan_loss_alpha: 1.


# network parameters
netG:
  input_dim: 3
  ngf: 32

netD:
  input_dim: 3
  ndf: 64
